/*
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
Header header
string[] joint_names
trajectory_msgs/JointTrajectoryPoint desired
trajectory_msgs/JointTrajectoryPoint actual
trajectory_msgs/JointTrajectoryPoint error
*/

using Newtonsoft.Json;
using CSI.ROS.Messages.Standard;
using CSI.ROS.Messages.Trajectory;

namespace CSI.ROS.Messages.Control
{
    public class FollowJointTrajectoryFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "control_msgs/FollowJointTrajectoryFeedback";

        public Header header;
        public String[] joint_names;
        public JointTrajectoryPoint desired;
        public JointTrajectoryPoint actual;
        public JointTrajectoryPoint error;

        public FollowJointTrajectoryFeedback()
        {
            header = new Header();
            joint_names = new String[] { };
            desired = new JointTrajectoryPoint();
            actual = new JointTrajectoryPoint();
            error = new JointTrajectoryPoint();
        }
    }
}

